"""Generate a clean standalone supplement from authoritative revised figure blocks."""
import hashlib
import re
from pathlib import Path
from common import ROOT, OUT
from probe_checkpoint import atomic_json, file_identity


def extract_extended_figures(text):
    figures = []
    for body in re.findall(r'\\begin\{figure\}(?:\[[^]]*\])?(.*?)\\end\{figure\}', text, flags=re.S):
        labels = re.findall(r'\\label\{([^}]+)\}', body)
        if not any(re.fullmatch(r'ed\d+', label) for label in labels):
            continue
        if len(labels) != 1 or 'Alt text:' not in body:
            raise ValueError('Supplement figure requires exactly one label and alt text')
        figures.append((labels[0], body))
    expected = [f'ed{i}' for i in range(1, 12)]
    if [label for label, _ in figures] != expected:
        raise ValueError('Expected ordered ED1 through ED11 exactly once')
    references = {ref for _, body in figures for ref in re.findall(r'\\ref\{([^}]+)\}', body)}
    if not references <= set(expected):
        raise ValueError(f'Unresolved standalone references: {references-set(expected)}')
    if any(r'\cite' in body for _, body in figures):
        raise ValueError('Supplement bibliography must be handled explicitly')
    return figures


def main():
    source = ROOT/'revision/manuscript/sn-article.tex'
    figures = extract_extended_figures(source.read_text())
    methods = ROOT/'revision/manuscript/supplementary-methods.tex'
    bibliography = ROOT/'revision/manuscript/sn-bibliography.bib'
    methods_text = methods.read_text()
    if not methods_text.startswith(r'\section*{Supplementary Methods}'):
        raise ValueError('Missing supplementary Methods heading')
    refs = set(re.findall(r'\\ref\{([^}]+)\}', methods_text))
    if not refs <= {label for label, _ in figures}:
        raise ValueError(f'Unresolved Methods figure references: {refs}')
    directory = ROOT/'revision/supplement'
    directory.mkdir(parents=True, exist_ok=True)
    preamble = r'''% Generated by scripts/revision/build_supplement.py; edit manuscript source instead.
\documentclass[10pt,a4paper]{article}
\usepackage[margin=0.9in]{geometry}
\usepackage[T1]{fontenc}
\usepackage{graphicx}
\usepackage{amsmath,amssymb,textcomp}
\usepackage[font=small,labelfont=bf]{caption}
\usepackage[hidelinks]{hyperref}
\graphicspath{{../figures/}{../submitted/}}
\newcommand{\rev}[1]{#1}
\renewcommand{\figurename}{Extended Data Fig.}
\begin{document}
\begin{titlepage}
\centering
\vspace*{1in}
{\Large\bfseries Supplementary Materials\par}
\vspace{0.4in}
{\large Structure tokens modulate sparse features of protein language models\par}
\vspace{0.3in}
BIOINF-2026-2288\par
\vspace{0.3in}
Jacob L Steenwyk\par
\vspace{0.5in}
Extended Data Figures 1--11\par
Detailed Methods and references\par
\vfill
Working revision. No change highlighting is included.\par
Scientific and release checks remain tracked in the revision checklist.\par
Not yet submission-ready.\par
\end{titlepage}
'''
    sections = [preamble]
    manifest = {'source': file_identity(source, content=True),
                'methods_source': file_identity(methods, content=True),
                'bibliography': file_identity(bibliography, content=True),
                'generator': file_identity(Path(__file__), content=True),
                'scope': 'Clean revised ED1-ED11 and detailed Methods with references; not final scientific or journal certification.',
                'figures': []}
    for label, body in figures:
        images = re.findall(r'\\includegraphics(?:\[[^]]*\])?\{([^}]+)\}', body)
        identities = []
        for image in images:
            candidates = [directory/image, ROOT/'revision/figures'/image, ROOT/'revision/submitted'/image]
            found = next((p for p in candidates if p.is_file()), None)
            if found is None:
                raise FileNotFoundError(image)
            identities.append(file_identity(found, content=True))
        manifest['figures'].append({'label': label, 'body_sha256': hashlib.sha256(body.encode()).hexdigest(),
                                    'images': identities, 'alt_text_present': True})
        sections.append('\\begin{figure}[!ht]\n\\centering\n'+body+'\n\\end{figure}\n\\clearpage\n')
    sections.append('\\begingroup\n\\setlength{\\emergencystretch}{2em}\n'+methods_text+'\\par\\endgroup\n')
    sections.append('\\clearpage\n\\bibliographystyle{plain}\n\\bibliography{../manuscript/sn-bibliography}\n')
    sections.append('\\end{document}\n')
    target = directory/'supplement-clean.tex'
    target.write_text('\n'.join(sections))
    manifest['generated_source'] = file_identity(target, content=True)
    atomic_json(OUT/'supplement_manifest.json', manifest)
    print(f'Generated {target} with {len(figures)} figures')


if __name__ == '__main__':
    main()
