"""Generate an OUP-format working draft without changing authoritative prose."""
import re
import shutil
from pathlib import Path
from common import ROOT, OUT
from probe_checkpoint import atomic_json, file_identity
from build_main_only import make_main_source


def journal_source(source):
    main, references = make_main_source(source)
    front = main.split(r'\begin{document}', 1)[1].split(r'\maketitle', 1)[0]
    old_author = r'\author*[1]{\fnm{Jacob L} \sur{Steenwyk}}\email{jlsteenwyk@berkeley.edu}'
    if front.count(old_author) != 1 or front.count(r'\affil*[1]') != 1:
        raise ValueError('Author metadata changed; review OUP conversion')
    front = front.replace(old_author, r'\author[1,$\ast$]{Jacob L Steenwyk}')
    front = front.replace(r'\affil*[1]', r'\address[1]').replace(r'\city{Berkeley}', 'Berkeley')
    front = front.replace('[Article Title]', '[Protein feature vocabularies]')
    front = front.replace(r'\par\rev', r'\\\rev')
    front += '\n'+r'\corresp[$\ast$]{Corresponding author. \href{mailto:jlsteenwyk@berkeley.edu}{jlsteenwyk@berkeley.edu}}'+'\n'
    body = main.split(r'\maketitle', 1)[1]
    figures = re.findall(r'\\begin\{figure\}(?:\[[^]]*\])?.*?\\end\{figure\}', body, re.S)
    if len(figures) != 4:
        raise ValueError('Expected four main figures')
    for figure in figures:
        body = body.replace(figure, '', 1)
    body = body.replace(r'\section*{Figures and figure legends}', '')
    for command in (r'\newpage', r'\clearpage', r'\FloatBarrier', r'\bigskip'):
        body = body.replace(command, '')
    body = '\n'.join(line for line in body.splitlines() if not line.lstrip().startswith('%'))
    for index, figure in enumerate(figures, 1):
        figure = re.sub(r'\\begin\{figure\}(?:\[[^]]*\])?', lambda _: r'\begin{figure*}[t]', figure)
        figure = figure.replace(r'\end{figure}', r'\end{figure*}')
        figure = re.sub(r'\\includegraphics\[[^]]*\]',
            lambda _: r'\includegraphics[width=\textwidth,height=.46\textheight,keepaspectratio]', figure)
        first_ref = body.find(r'\ref{fig'+str(index)+'}')
        if first_ref < 0:
            raise ValueError('Missing main-figure citation')
        paragraph_end = body.find('\n\n', first_ref)
        if paragraph_end < 0:
            raise ValueError('Unterminated figure-citing paragraph')
        body = body[:paragraph_end]+'\n\n'+figure+body[paragraph_end:]
    body = body.replace(r'\bibliography{sn-bibliography}',
        r'\bibliographystyle{oup-abbrvnat}'+'\n'+r'\bibliography{../manuscript/sn-bibliography}')
    # The journal specifies author-date references; use parenthetical citations.
    body = body.replace(r'\cite{', r'\citep{')
    preamble = r'''% Generated by build_journal_manuscript.py; edit manuscript/sn-article.tex.
\documentclass[numsec,webpdf,modern,large]{oup-authoring-template}
\ifdefined\pdfminorversion\pdfminorversion=5\fi
\usepackage{graphicx,amsmath,amssymb,xcolor}
\usepackage{oup-local-compat}
\setlength{\emergencystretch}{2em}
\graphicspath{{../submitted/}{../figures/}}
\newcommand{\societylogo}{}
\newcommand{\rev}[1]{\ifdefined\revisionmarked\textcolor{red}{#1}\else#1\fi}
\pdfstringdefDisableCommands{\def\rev#1{#1}}
\begin{document}
\journaltitle{Bioinformatics}
\DOI{}
\copyrightyear{}
\pubyear{}
\vol{}
\issue{}
\access{}
\appnotes{Original Paper: working revision}
\firstpage{1}
'''
    return preamble+front+'\n\\revisionfitheader\n\\maketitle\n'+body, references


def main():
    source = ROOT/'revision/manuscript/sn-article.tex'
    text, references = journal_source(source.read_text())
    directory = ROOT/'revision/journal'
    directory.mkdir(exist_ok=True)
    vendor = ROOT/'revision/vendor/oup-authoring-template'
    assets = []
    for name in ('oup-authoring-template.cls', 'oup-abbrvnat.bst'):
        shutil.copyfile(vendor/name, directory/name)
        assets.append(file_identity(directory/name, content=True))
    compatibility = ROOT/'revision/manuscript/oup-local-compat.sty'
    shutil.copyfile(compatibility, directory/compatibility.name)
    assets.append(file_identity(directory/compatibility.name, content=True))
    target, marked = directory/'bioinformatics.tex', directory/'bioinformatics-marked.tex'
    target.write_text(text)
    marked.write_text('\\def\\revisionmarked{1}\n\\input{bioinformatics.tex}\n')
    atomic_json(OUT/'journal_manuscript_manifest.json', {
        'scope': 'OUP template conversion and working layout; not certified page-limit compliance or final scientific content.',
        'source': file_identity(source, content=True), 'generator': file_identity(Path(__file__), content=True),
        'publisher_journal_list': file_identity(ROOT/'revision/vendor/OUP_LaTeX_supported_jnls.xlsx', content=True),
        'assets': assets, 'generated': [file_identity(p, content=True) for p in (target, marked)],
        'references': references, 'layout': 'numsec,webpdf,modern,large; author-date',
        'figure_handling': 'Unchanged captions/alt text; full-width floats after first-citing paragraphs; aspect-preserving image size caps.'})
    print('Generated clean/marked OUP working drafts')


if __name__ == '__main__':
    main()
