"""Generate main-only clean/marked sources without duplicating supplementary figures."""
import re
from pathlib import Path
from common import ROOT, OUT
from probe_checkpoint import atomic_json, file_identity
from build_supplement import extract_extended_figures


def make_main_source(text):
    figures = extract_extended_figures(text)
    numbers = {label: str(index+1) for index, (label, _) in enumerate(figures)}
    marker = r'\section*{Extended Data}'
    if text.count(marker) != 1:
        raise ValueError('Expected one Extended Data section')
    main = text.split(marker)[0]
    replacements = {}

    def replace(match):
        label = match.group(1)
        if label not in numbers:
            raise ValueError(f'Unknown supplementary figure reference: {label}')
        replacements[label] = replacements.get(label, 0)+1
        return numbers[label]

    # Separate-document references are printed numbers, not broken internal links.
    main = re.sub(r'\\ref\{(ed\d+)\}', replace, main)
    labels = re.findall(r'\\label\{([^}]+)\}', main)
    references = re.findall(r'\\ref\{([^}]+)\}', main)
    if set(references)-set(labels):
        raise ValueError('Unresolved main-document references')
    bodies = re.findall(r'\\begin\{figure\}(?:\[[^]]*\])?(.*?)\\end\{figure\}', main, re.S)
    figure_labels = [re.findall(r'\\label\{([^}]+)\}', body) for body in bodies]
    if figure_labels != [[f'fig{i}'] for i in range(1, 5)] or any('Alt text:' not in body for body in bodies):
        raise ValueError('Expected four ordered main figures with alt text')
    main = '% Generated by scripts/revision/build_main_only.py; edit sn-article.tex instead.\n'+main.rstrip()+'\n\\end{document}\n'
    return main, {'supplement_figure_numbers': numbers, 'replaced_reference_counts': replacements,
                  'main_figure_labels': figure_labels}


def main():
    directory = ROOT/'revision/manuscript'
    source = directory/'sn-article.tex'
    main_text, refs = make_main_source(source.read_text())
    target = directory/'sn-article-main.tex'
    marked = directory/'sn-article-main-marked.tex'
    target.write_text(main_text)
    marked.write_text('\\def\\revisionmarked{1}\n\\input{sn-article-main.tex}\n')
    record = {'scope': 'Source separation and supplementary reference numbering; not journal-template or scientific certification.',
              'source': file_identity(source, content=True), 'generator': file_identity(Path(__file__), content=True),
              'generated_source': file_identity(target, content=True), 'marked_wrapper': file_identity(marked, content=True),
              'references': refs}
    atomic_json(OUT/'main_only_manifest.json', record)
    print(f'Generated main-only clean/marked sources with {len(refs["main_figure_labels"])} figures')


if __name__ == '__main__':
    main()
